/** Medium tuning. All durations are simulation seconds, all scores are damage equivalents. */
export const BOT = {
	thinkingSeconds: 2,
	regardSeconds: 0.6,
	candidatesPerStep: 24,
	maxPlanningSeconds: 2,
	shotHorizon: 8,
	movementHorizon: 3,
	shortWalk: 0.65,
	mediumWalk: 1.5,
	maxRepositions: 1,
	stopMovementBelow: 12,
	fallbackBelow: 5,
	improvementRequired: 8,
	movementTimeCost: 2,
	movementDamageCost: 2,
	exposureWeight: 0.12,
	angleStep: Math.PI / 18,
	powerStep: 0.1,
	refineAngle: Math.PI / 36,
	refinePower: 0.04,
	angleError: Math.PI / 90,
	powerError: 0.025,
	enemyKillBonus: 28,
	friendlyWeight: 1.5,
	selfWeight: 2,
	friendlyKillPenalty: 65,
	selfKillPenalty: 100,
	uselessScore: -25,
} as const;
