/** World units are pixels, seconds and radians. All gameplay tuning lives here. */
export const WEAPON = {
	aimMin: -Math.PI / 2,
	aimMax: Math.PI / 2,
	aimSpeed: 1.4,
	defaultAim: Math.PI / 4,
	chargeDuration: 1.4,
	gravity: 260,
	windAcceleration: 100,
	maxMotionStep: 0.75,
	maxLifetime: 15,
	worldMargin: 400,
	verticalWorldMargin: 1200,
	cameraMaxRise: 1200,
	launchGap: 2,
	collisionSkin: 0.02,
	waterSkin: 0.1,
	restProbe: 0.15,
	restNormalMin: 0.15,
	submergedHorizontalRetention: 0.3,
	fuseEpsilon: 1e-9,
	bazooka: { radius: 3, minSpeed: 70, maxSpeed: 680 },
	grenade: {
		radius: 4,
		minSpeed: 55,
		maxSpeed: 440,
		restitution: 0.52,
		tangentRetention: 0.78,
		settleSpeed: 24,
	},
	skip: {
		minSpeed: 230,
		maxVerticalRatio: 0.28,
		horizontalRetention: 0.78,
		verticalRetention: 0.6,
		minLift: 35,
		maxCount: 2,
		submergedLifetime: 0.3,
	},
	blast: { radius: 75, terrainRadius: 42, maxDamage: 50, knockback: 390 },
	death: { radius: 38, terrainRadius: 22, maxDamage: 25, knockback: 190 },
	fxDuration: 0.55,
	reticleDistance: 90,
} as const;
